version: 2.1

executors:
  unity_exec:
    docker:
      - image: gableroux/unity3d:2018.3.4f1
    environment:
      BUILD_NAME: ExampleProjectName

.test: &test
  executor: unity_exec
  steps:
    - checkout
    - run:
        name: Fetching build scripts
        command: |
          apt update && apt install -y git 
          git clone https://github.com/qwertyuu/unity-ci-build-scripts.git
          cp -r unity-ci-build-scripts/Assets/Editor ./Assets
          cp -r unity-ci-build-scripts/ci ./ci
    - run: 
        name: Converting Unity license
        command: chmod +x ./ci/before_script.sh && ./ci/before_script.sh
    - run:
        name: Running tests
        command: chmod +x ./ci/test.sh && ./ci/test.sh
    - store_artifacts:
        path: $(pwd)/$TEST_PLATFORM-results.xml

.build: &build
  executor: unity_exec
  steps:
    - checkout
    - run:
        name: Fetching build scripts
        command: |
          apt update && apt install -y git 
          git clone https://github.com/qwertyuu/unity-ci-build-scripts.git
          if [ $(git ls-remote https://github.com/qwertyuu/unity-ci-build-scripts.git 2018.3.4f1 | wc -l) -eq 1 ]; then cd unity-ci-build-scripts && git pull origin 2018.3.4f1 && cd ..; fi
          cp -r unity-ci-build-scripts/Assets/Editor ./Assets
          cp -r unity-ci-build-scripts/ci ./ci
    - run: 
        name: Converting Unity license
        command: chmod +x ./ci/before_script.sh && ./ci/before_script.sh
    - run:
        name: Building game binaries
        command: chmod +x ./ci/build.sh && ./ci/build.sh
    - run: 
        name: Zipping build
        command: apt update && apt -y install zip && zip -r "build.zip" ./Builds/
    - store_artifacts:
        path: build.zip

jobs:
  test_editmode:
    <<: *test
    environment:
      TEST_PLATFORM: editmode
  test_playmode:
    <<: *test
    environment:
      TEST_PLATFORM: playmode

  build_windows:
    <<: *build
    environment:
      BUILD_TARGET: StandaloneWindows64
  build_osx:
    <<: *build
    environment:
      BUILD_TARGET: StandaloneOSX
  build_linux:
    <<: *build
    environment:
      BUILD_TARGET: StandaloneLinux64
  build_webgl:
    <<: *build
    environment:
      BUILD_TARGET: WebGL
          
workflows:
  version: 2
  build:
    jobs:
      - build_windows
